module ResortData
  class Idaho
    RESORTS = [{
      name: 'Bald Mountain',
      location: 'Clearwater County, Idaho, U.S.',
      latitude: 46.57,
      longitude: -115.87,
      vertical: 684,
      elevation_top: 4400,
      elevation_base: 3716,
      skiable_area: 140,
      runs: 15,
      chairlifts: 2,
      average_snowfall: 100,
      night_skiing: false,
      snowmaking: false,
      website: 'http://skibaldmountain.com',
      green_percentage: 25,
      blue_percentage: 40,
      black_percentage: 35
    }, {
      name: 'Bogus Basin',
      location: 'Boise National Forest Boise County, Idaho, U.S.',
      latitude: 43.764,
      longitude: -116.104,
      vertical: 1790,
      elevation_top: 7582,
      elevation_base: 6150,
      skiable_area: 2600,
      runs: 53,
      chairlifts: 7,
      average_snowfall: 225,
      night_skiing: true,
      snowmaking: true,
      website: 'http://bogusbasin.org',
      green_percentage: 22,
      blue_percentage: 45,
      black_percentage: 33
    }, {
      name: 'Brundage Mountain',
      location: 'Payette National Forest Adams & Valley counties, Idaho, U.S.',
      latitude: 45.005,
      longitude: -116.155,
      vertical: 1800,
      elevation_top: 7640,
      elevation_base: 5840,
      skiable_area: 1500,
      runs: 46,
      chairlifts: 5,
      average_snowfall: 325,
      night_skiing: false,
      snowmaking: false,
      website: 'http://brundage.com',
      green_percentage: 20,
      blue_percentage: 50,
      black_percentage: 30
    }, {
      name: 'Cottonwood Butte',
      location: 'Idaho County, Idaho',
      latitude: 46.0755,
      longitude: -116.4528,
      vertical: 845,
      elevation_top: 5730,
      elevation_base: 4721,
      skiable_area: 260,
      runs: 7,
      chairlifts: 2,
      average_snowfall: 45,
      night_skiing: true,
      snowmaking: false,
      website: 'http://cottonwoodbutte.org',
      green_percentage: nil,
      blue_percentage: nil,
      black_percentage: nil
    }, {
      name: 'Kelly Canyon',
      location: 'Targhee National Forest Jefferson County & Madison County, Idaho',
      latitude: 43.3845,
      longitude: -111.3748,
      vertical: 1000,
      elevation_top: 6600,
      elevation_base: 5600,
      skiable_area: 640,
      runs: 26,
      chairlifts: 4,
      average_snowfall: 200,
      night_skiing: true,
      snowmaking: true,
      website: 'http://skikelly.com',
      green_percentage: 35,
      blue_percentage: 45,
      black_percentage: 20
    }, {
      name: 'Little Ski Hill',
      location: 'Adams County, Idaho',
      latitude: 44.5548,
      longitude: -116.0947,
      vertical: 405,
      elevation_top: 5600,
      elevation_base: 5195,
      skiable_area: 50,
      runs: nil,
      chairlifts: 1,
      average_snowfall: nil,
      night_skiing: true,
      snowmaking: false,
      website: 'http://littleskihill.org',
      green_percentage: nil,
      blue_percentage: nil,
      black_percentage: nil
    }, {
      name: 'Lost Trail Powder Mountain',
      location: 'Lost Trail Pass Lemhi County, Idaho',
      latitude: 45.69,
      longitude: -113.95,
      vertical: 1800,
      elevation_top: 8200,
      elevation_base: 6400,
      skiable_area: 900,
      runs: 45,
      chairlifts: 8,
      average_snowfall: 300,
      night_skiing: false,
      snowmaking: false,
      website: 'http://losttrail.com',
      green_percentage: 20,
      blue_percentage: 60,
      black_percentage: 20
    }, {
      name: 'Lookout Pass Ski and Recreation Area',
      location: 'Shoshone County, Idaho',
      latitude: 47.453,
      longitude: -115.707,
      vertical: 1150,
      elevation_top: 5650,
      elevation_base: 4500,
      skiable_area: 540,
      runs: 34,
      chairlifts: 4,
      average_snowfall: 400,
      night_skiing: false,
      snowmaking: false,
      website: 'http://skilookout.com',
      green_percentage: 20,
      blue_percentage: 50,
      black_percentage: 30
    }, {
      name: 'Magic Mountain',
      location: 'Sawtooth National Forest Twin Falls Co., Idaho',
      latitude: 42.1117,
      longitude: -114.1710,
      vertical: 700,
      elevation_top: 7240,
      elevation_base: 6540,
      skiable_area: 120,
      runs: 11,
      chairlifts: 3,
      average_snowfall: 230,
      night_skiing: false,
      snowmaking: false,
      website: 'http://magicmountainresort.com',
      green_percentage: nil,
      blue_percentage: nil,
      black_percentage: nil
    }, {
      name: 'Pebble Creek',
      location: 'Caribou National Forest Bannock County, Idaho',
      latitude: 42.4641,
      longitude: -112.9353,
      vertical: 2911,
      elevation_top: 9271,
      elevation_base: 6360,
      skiable_area: 1100,
      runs: 54,
      chairlifts: 3,
      average_snowfall: 250,
      night_skiing: true,
      snowmaking: true,
      website: 'http://pebblecreekskiarea.com',
      green_percentage: 12,
      blue_percentage: 35,
      black_percentage: 53
    }, {
      name: 'Pomerelle',
      location: 'Sawtooth National Forest Cassia County, Idaho',
      latitude: 42.318,
      longitude: -113.608,
      vertical: 1002,
      elevation_top: 8762,
      elevation_base: 7760,
      skiable_area: 500,
      runs: 24,
      chairlifts: 3,
      average_snowfall: 500,
      night_skiing: true,
      snowmaking: false,
      website: 'http://pomerelle.com',
      green_percentage: 20,
      blue_percentage: 50,
      black_percentage: 30
    }, {
      name: 'Rotarun Ski Area',
      location: 'Blaine County, Idaho',
      latitude: 43.2951,
      longitude: -114.21576,
      vertical: 475,
      elevation_top: 5895,
      elevation_base: 5420,
      skiable_area: nil,
      runs: nil,
      chairlifts: 1,
      average_snowfall: nil,
      night_skiing: true,
      snowmaking: nil,
      website: 'http://rotarunski.com',
      green_percentage: nil,
      blue_percentage: nil,
      black_percentage: nil
    }, {
      name: 'Schweitzer',
      location: 'Bonner County, Idaho',
      latitude: 48.367,
      longitude: -116.623,
      vertical: 2440,
      elevation_top: 6400,
      elevation_base: 3960,
      skiable_area: 2900,
      runs: 92,
      chairlifts: 7,
      average_snowfall: 300,
      night_skiing: true,
      snowmaking: true,
      website: 'http://schweitzer.com',
      green_percentage: 20,
      blue_percentage: 40,
      black_percentage: 40
    }, {
      name: 'Silver Mountain',
      location: 'Kellogg, Idaho',
      latitude: 47.495,
      longitude: -116.135,
      vertical: 2197,
      elevation_top: 6297,
      elevation_base: 4100,
      skiable_area: 1600,
      runs: 67,
      chairlifts: 8,
      average_snowfall: 300,
      night_skiing: true,
      snowmaking: false,
      website: 'http://silvermt.com',
      green_percentage: 20,
      blue_percentage: 40,
      black_percentage: 40
    }, {
      name: 'Snowhaven',
      location: 'Idaho County, Idaho',
      latitude: 45.528,
      longitude: -116.524,
      vertical: 400,
      elevation_top: 5600,
      elevation_base: 5200,
      skiable_area: 40,
      runs: 9,
      chairlifts: 2,
      average_snowfall: 60,
      night_skiing: false,
      snowmaking: false,
      website: nil,
      green_percentage: 75,
      blue_percentage: 25,
      black_percentage: 0
    }, {
      name: 'Soldier Mountain',
      location: 'Sawtooth National Forest Camas County, Idaho',
      latitude: 43.485,
      longitude: -114.830,
      vertical: 1425,
      elevation_top: 7177,
      elevation_base: 5752,
      skiable_area: 1150,
      runs: 36,
      chairlifts: 3,
      average_snowfall: 100,
      night_skiing: false,
      snowmaking: false,
      website: 'http://soldiermountain.com',
      green_percentage: 28,
      blue_percentage: 25,
      black_percentage: 47
    }, {
      name: 'Tamarack Resort',
      location: 'Valley County, Idaho',
      latitude: 44.4027,
      longitude: -116.718,
      vertical: 2760,
      elevation_top: 7660,
      elevation_base: 4900,
      skiable_area: 1100,
      runs: 39,
      chairlifts: 6,
      average_snowfall: 300,
      night_skiing: false,
      snowmaking: true,
      website: 'http://tamarackidaho.com',
      green_percentage: 15,
      blue_percentage: 56,
      black_percentage: 29
    }]
  end
end
